
name: Hello NueXini

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Initialization
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/NueXini/BuildOpenWrt/master/.github/workflows/BuildEnviroment)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean

    - name: Hello World
      run: |
        releasetag=$(cat ./config/releasetag | awk 'NR==1')
        git clone $releasetag nuexini

    - name: Update & Install feeds
      run: |
        chmod +x ./sh/*.sh
        cd nuexini
        ../sh/Hello_NueXini.sh
        ./scripts/feeds update -a && ./scripts/feeds install -a
        [ -e ../config/.config ] && mv ../config/.config ./.config
        ../sh/Hi_NueXini.sh
      
    - name: Download
      run: |
        cd nuexini
        make defconfig
        make download -j8
        rm -rf $(find ./dl/ -size -1024c)

    - name: Compile
      run: |
        cd nuexini
        make -j8 || make -j1 V=sc
    
    - name: One more thing
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Firmware
        path: nuexini/bin/targets

    - name: Last thing
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Bin
        path: nuexini/bin

##### $GITHUB_WORKSPACE ######
###### ###### ###### ###### ###### 
