
name: Hi NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: '.config'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: BuildEnviroment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y update
        # sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/NueXini/BuildOpenWrt/master/.github/workflows/BuildEnviroment)
        sudo -E apt-get -y install $(cat ./.github/workflows/BuildEnviroment)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean

    - name: Clone
      run: |
        releasetag=$(cat ./config/releasetag | awk 'NR==1')
        git clone $releasetag dd
        
    - name: Update & Install feeds
      run: |
        chmod +x ./sh/*.sh
        cd dd
        ../sh/Hello_NueXini.sh
        ./scripts/feeds update -a && ./scripts/feeds install -a
        [ -e ../config/${{ github.event.inputs.config }} ] && cp -rf ../config/${{ github.event.inputs.config }} ./.config
        ../sh/Hi_NueXini.sh
        
    - name: Hi NueXini
      uses: rdp-studio/ssh2actions@v2.0.0
      
    - name: Preparation
      run: |
        cd dd
        mkdir -p ./nuexini
        cp -rf ./.config ./nuexini/
        if [ -d "./bin" ]; then
                cp -rf ./bin ./nuexini/
        fi

    - name: Last thing
      uses: actions/upload-artifact@v2.3.1
      with:
        name: config
        path: dd/nuexini

##### $GITHUB_WORKSPACE ######
###### ###### ###### ###### ###### 
#    - name: Hi NueXini
#      uses: rdp-studio/ssh2actions@v2.0.0
#      with:
#        mode: ngrok
#      env:
#        SSH_PASSWORD: 'nuexini'
#        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
