
name: Hi NueXini

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: BuildEnviroment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/NueXini/BuildOpenWrt/master/.github/workflows/BuildEnviroment)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean

    - name: Clone
      run: |
        releasetag=$(cat ./config/releasetag | awk 'NR==1')
        git clone $releasetag dd
        
    - name: Update & Install feeds
      run: |
        chmod +x ./sh/*.sh
        cd dd
        ../sh/Hello_NueXini.sh
        ./scripts/feeds update -a && ./scripts/feeds install -a
        [ -e ../config/.config ] && mv ../config/.config ./.config
        ../sh/Hi_NueXini.sh
        
    - name: Hi NueXini
      uses: P3TERX/ssh2actions@v1.0.0
      
    - name: Preparation
      run: |
        cd dd
        mkdir -p ./nuexini
        cp -rf ./.config ./nuexini/
        if [ -d "./bin" ]; then
                cp -rf ./bin ./nuexini/
        fi

    - name: Last thing
      uses: actions/upload-artifact@v2.3.1
      with:
        name: config
        path: dd/nuexini
        
    - name: Hi NueXini
      run: |
        curl -fsSL git.io/cowtransfer | sh
        ./cowtransfer-uploader -s -p 8 dd/config.zip 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        

##### $GITHUB_WORKSPACE ######
###### ###### ###### ###### ###### 
